project_id = "cpggicxvmgyljvoxlpnu"

[functions.stripe-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false